name: Generate the Feed
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup PY
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Dependencies
        run:  |
          python -m pip install --upgrade pip
          pip install pyyaml
      - name: Generate Feed
        run: python feed.py
      - name: Push
        run:  |
          git config user.name github-actions
          git congif user.email github-actions@github.com
          git add .
          git commit -m "Feed update [action]"
          git push
